<?php

declare(strict_types=1);

namespace App\Helpers\Studio;

use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;
use App\Models\Module;

class ViewGenerator
{
    public static function generate(Module $module): bool
    {
        $folder = resource_path('views/modules/' . Str::snake($module->fullname));
        $file   = $folder . '/index.blade.php';

        if (File::exists($file)) {
            return false;
        }

        if (! File::exists($folder)) {
            File::makeDirectory($folder, 0755, true);
        }

        $name = $module->fullname;
        File::put($file, <<<BLADE
        {{-- Module: {$name} — generated by Studio. Edit this file to customise the view. --}}
        <div class="container mx-auto px-4 py-6">
            <h1 class="text-2xl font-bold mb-4">{$name}</h1>
            <p class="text-gray-500">
                This view was auto-generated by Studio.
                Replace this content with your custom Blade template.
            </p>
        </div>
        BLADE);

        return true;
    }

    public static function remove(Module $module): bool
    {
        $folder = resource_path('views/modules/' . Str::snake($module->fullname));
        $file   = $folder . '/index.blade.php';

        if (! File::exists($file)) {
            return false;
        }

        File::delete($file);

        // [L4] File::files() only checks immediate files; also check for subdirectories
        // so a folder containing only sub-folders is not mistakenly deleted.
        if (File::isDirectory($folder) && empty(File::files($folder)) && empty(File::directories($folder))) {
            File::deleteDirectory($folder);
        }

        return true;
    }
}